### PR TITLE
httplug

### PR DESCRIPTION
**Pull request by makasim**
https://github.com/Payum/Payum/pull/505

### CODE REVIEW

**Comment by makasim** [comment]
@Nyholm I tried to add `php-http/message php-http/guzzle6-adapter` but it does not work. I am getting `Puli Factory is not available` exception.

**Comment by Nyholm** [comment]
You have two options:

1) Use discovery: http://docs.php-http.org/en/latest/discovery.html#puli-factory-is-not-available
2) Specify `httplug.client` and `httplug.message_factory` (https://github.com/Nyholm/Payum/blob/httplug/src/Payum/Core/Resources/docs/get-it-started.md#configphp)

**Comment by makasim** [comment]
I mean the [doc](https://github.com/Payum/Payum/pull/505/files#diff-c4d8485e8ee62bf686dc77336617dd86R16) says next `php composer.phar require payum/offline php-http/message php-http/guzzle6-adapter`. I expect if I do it I am fine and everything works fine.

**Comment by Nyholm** [comment]
Sorry about that. It should be more clear some how. Also see this [doc](https://github.com/Payum/Payum/pull/505/files#diff-c4d8485e8ee62bf686dc77336617dd86R66). 

If it should completely work out of the box. We must require `puli/composer-plugin`. (Today it is optional). But Puli is still in beta and some developers might not want to install Puli if they are not using it.

**Comment by makasim** [comment]
@Nyholm Could we require something like php-http/curl-client by default, something really lightweight and allow user to overwrite things later. I worry about the process a bit, it gets really hard to do.

**Comment by Nyholm** [comment]
> I worry about the process a bit, it gets really hard to do.

I understand the concern. Httplug is a new thing and it might be strange to use it at first. But I strongly believe this is how every library is going to use it within a year. There is even plans to make Httplug a PSR. 

Adding a lightweight adapter is not an ideal solution. That would add an unnecessary dependency. I would much rather try to improve the documentation to make this migrations as smooth as possible. 

What do you think?

**Comment by makasim** [comment]
It makes a process of setting up the payum a lot more complicated, and while it is still easy to do in plain php by instantiating the http client and passing it the config. But what about the symfony and the payum bundle? User has to create a service with http client himself, and correctly instrutruct payum bundle to use it. 

I predict a lot of question will come from many people. They will be confused by all that stuff like discovery, different options etc.

I am still big fan of this, but the solutions should be easy still allowing advanced options.

**Comment by Nyholm** [comment]
>  But what about the symfony and the payum bundle?

We should add options to inject services. See the [docs](http://docs.php-http.org/en/latest/integrations/symfony-bundle.html#usage-for-reusable-bundles). It will actually be easier with Symfony bundles. 

> I predict a lot of question will come from many people. They will be confused by all that stuff like discovery, different options etc. 

You might be correct, there will be some questions. 

Do you suggest that instead of using discovery we fallback on the installed cULR adapter?

**Comment by makasim** [comment]
I am not sure, let me play with it for a while. I have to better understand the concepts.

**Pull request merged**
